### ISSUE TITLE
Calling from secondary alignments

### ISSUE THREAD

**Issue by gilhornung** [nygenome/lancet#17]
Hi Giuseppe,

I noticed several cases where lancet reported a variant, and based on the IGV image (see example below), all the variants appear on secondary alignments. Is there a way to ask lancet not to use secondary alignments to call variants?

Thank you,

Gil

bam file with the problematic variant:
https://owncloud.incpm.weizmann.ac.il/index.php/s/HltGOlzT6wegHtp/download?path=%2F&files=lamc2.bam

IGV image:
![lamc2_igv](https://user-images.githubusercontent.com/25452585/38694523-964c44dc-3e92-11e8-9459-37529d106b70.png)

**Comment by gnarzisi** [comment]
Currently there is no option to not use secondary alignments. I may include an option for this in the future if there is enough evidence that variants called from these reads are usually false-positives.

In your specific example, however, it looks like these are supplementary alignments that have been marked as secondary (using the -M option in BWA). This means that, instead of the read mapping to multiple places in the genome (e.g., due to repeats), this is actually a split alignment where a portion of the read maps to one place while the rest of the bases map to another place. As such, those reads should be used for variant calling in general. As indication of the fact that they are supplementary, the alignments are shorter (63bp), contain hard clippings, and their supplementary alignment follow the sam pattern.

**Comment by gnarzisi** [comment]
Also note that, although lancet does not filter secondary alignments based on their alignment flag, reads that are highly likely to be multi-mapped are filtered using a combination of the AS and XS tags.

**Comment by gnarzisi** [comment]
What is your rationale to assume that these 4 (supplementary alignment) reads are PCR duplicates? Also, as I mentioned before, supplementary alignments can represent true mutations, especially structural variations. 

For (real) secondary alignments, it may be worth exploring the impact of using or discarding them for variant calling. If it becomes a serious issue, I may add an option to allow skipping these alignments. But for now I feel that this has low priority.

**Comment by gnarzisi** [comment]
The latest release provides a new command line parameter to request only primary alignments to be used for variant calling. Cheers!

**Comment by ahwanpandey** [comment]
Hello,

Does lancet ignore duplicate marked reads by default?

Thanks!

**Comment by gnarzisi** [comment]
Yes. As long as their a correctly marked in the BAM file.
