### ISSUE TITLE
Lancet fails on IonTorrent targeted single-end data

### ISSUE THREAD

**Issue by HLAmolec** [nygenome/lancet#28]
Hello,
I've tested Lancet on small bam files containing indels generated by IonTorrent.  Lancet failed to detect these indels.  Perhaps Lancet only works with NGS pair-end data?

Thank you.

**Comment by gnarzisi** [comment]
Thank you for reporting the issue.

as we discussed offline, lancet was never tested on ion torrent data, so results are unpredictable. 
After some debugging, the problem seems to be mapper related. The ion torrent mapper (tmap) uses XA tag in the BAM/SAM format to store the algorithm that produced the mapping (https://github.com/iontorrent/TMAP/blob/master/doc/tmap-book.pdf), while bwa (at least the older “aln” version) uses the same XA tag to list the alternative hits for the read. 

I pushed on GitHub a new commit where I included an optional flag to skip reads with multiple hits listed in the XA tag (BWA only). This flag is turned off by default which means that the XA flag would be ignored. Please let me know if works.

To get the most recent version of the code that includes this option, simply pull the most recent version of the code from the repo:

`git clone git://github.com/nygenome/lancet.git`
